### ISSUE TITLE
Problème de version Application JAVA à MAVEN

### ISSUE THREAD

**Issue by bruckmannf** [TomLeal/ProjetSIO2JavaPDF#1]
J'ai voulu reprendre votre projet sauf que mon application est de format "JAVA" sauf que le mien est de format "MAVEN".
Donc le projet ne marche pas et nécessite d'ajouter un "dependencies", c'est à dire : 
- clique droit sur "Dependencies" puis "Add dependencies",
- cherchez "itextpdf 5.5.13.1",
- vous tomberez sur "com.itextpdf : itextpdf",
- prenez la version dites précédemment,
Le projet marchera parfaitement !

**Comment by TomLeal** [comment]
Merci de votre collaboration, j'ai ajouté ceci dans la documentation.
